apiVersion: v1
kind: Service
metadata:
  name: artp-a360-api-service
  namespace: devspprod
spec:
  selector:
    app: artp-a360-api
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3003
  type: NodePort
