kind: Service
apiVersion: v1
metadata:
  name: shell-service  
  namespace: devspprod  
spec:
  selector:
    app: shell
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 3002  
  type: NodePort  